version: "3.8"
services:
  app:
    build:
      context: .
    tty: true
    volumes: &volumes # configs
      - type: bind
        source: ./configs/whitelist.json
        target: /code/whitelist.json
      - type: bind
        source: ./configs/banned-ips.json
        target: /code/banned-ips.json
      - type: bind
        source: ./configs/banned-players.json
        target: /code/banned-players.json
      - type: bind
        source: ./configs/ops.json
        target: /code/ops.json
      - type: bind
        source: ./data/configs/usercache.json
        target: /code/usercache.json
      - type: bind
        source: ./data/configs/server.properties
        target: /code/server.properties
      - ./data/logs:/code/logs
      - ./data/world:/code/world

      - ./data/dynmap:/code/dynmap
      - ./data/plugins_LuckPerms:/code/plugins/LuckPerms
      - ./data/plugins_WorldEdit:/code/plugins/WorldEdit
      - ./data/plugins_WorldGuard:/code/plugins/WorldGuard
      - ./data/journeymap:/code/journeymap
    ports:
      - 25565:25565
      - 4567:4567
      - 8123:8123

  dynmap:
    image: mariadb:12.1
    environment:
      MARIADB_ROOT_PASSWORD: "dynmap"
      MARIADB_USER: "dynmap"
      MARIADB_PASSWORD: "dynmap"
      MARIADB_DATABASE: "dynmap"
    expose:
      - "3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
